fixtures:
    symlinks:
      pe_metrics_dashboard: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.25.1
      apt:
        repo: https://github.com/puppetlabs/puppetlabs-apt.git
        ref: 4.3.0
      grafana: 
        repo: https://github.com/voxpupuli/puppet-grafana.git
        ref: v4.5.0
    forge_modules:
