---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

.travis.yml:
  dist: 'xenial'
  bundler_args: -----without system_tests
  docker_sets:
    - set: docker/centos-7
      options:
    - set: docker/ubuntu-16.04
      options:
  branches:
    - /.*/

Gemfile:
  required:
    ':development':
      - gem: 'puppet-strings'
        version: '~> 2.0.0'
      - gem: 'toml-rb'
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: beaker
        version: '~> 4'
      - gem: beaker-puppet
        version: '~> 1.0'
      - gem: beaker-abs
        version: '~> 0.1'
      - gem: beaker-pe
      - gem: beaker-rspec
      - gem: beaker-docker
      - gem: beaker-vagrant

spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - "  c.default_facter_version = '3.14.0'"
    - "  c.after(:suite) do"
    - "    RSpec::Puppet::Coverage.report!"
    - "  end"
    - "end"

Rakefile:
  requires:
    - require: 'puppet-strings/tasks'
      conditional: "Bundler.rubygems.find_name('puppet-strings').any?"
