---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true

.travis.yml:
  bundle_args: --without system_tests
  docker_sets:
    - set: docker/centos-7
      options:
    - set: docker/ubuntu-16.04
      options:
  branches:
    - /.*/

Gemfile:
  required:
    ':system_tests':
      - gem: 'puppet-module-posix-system-r#{minor_version}'
        platforms: ruby
      - gem: beaker
        version: '~> 3.13'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.1'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION

spec/spec_helper.rb:
  mock_with: ':rspec'

spec/default_facts.yml:
  extra_facts:
    'osfamily': 'RedHat'
    'platform_tag': 'el-6-x86_64'
    'operatingsystem': 'CentOS'
    'lsbmajdistrelease': '6'
    'operatingsystemrelease': '6'
    'is_pe': 'true'
    'pe_concat_basedir': '/tmp/file'
    'platform_symlink_writable': true
    'puppetversion': '4.5.1'
    'aio_agent_version': '1.5.1'
    'memorysize': '1.00 GB'
    'processorcount': 1
    'id': 'root'
    'gid': 'root'
    'path': '/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin'
    'mountpoints':
      '/': {}
    'os':
      'family': 'RedHat'
      'name': 'CentOS'
      'release':
        'major': '6'
    'pe_server_version': '2016.4.5'
    'memory':
      'system':
          'total_bytes': 4294967296
    'processors':
      'count': 1
