---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

.travis.yml:
  branches:
    - /.*/
  use_litmus: true
  litmus:
    puppet_collection:
      - ---puppet5
      - puppet6
      - puppet7
    complex:
      - collection:
          puppet_collection:
            - puppet5
          provision_list:
            - travis_deb_legacy
            - travis_el
  includes:
    - env: PUPPET_GEM_VERSION="~> 7.0" CHECK=parallel_spec
      rvm: 2.7.2
      stage: spec

Gemfile:
  required:
    ':development':
      - gem: 'toml-rb'

spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - "  c.default_facter_version = '3.14.0'"
    - "  c.after(:suite) do"
    - "    RSpec::Puppet::Coverage.report!"
    - "  end"
    - "end"

Rakefile:
  requires:
    - require: 'puppet-strings/tasks'
      conditional: "Bundler.rubygems.find_name('puppet-strings').any?"
