---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

.travis.yml:
  branches:
    - /.*/
  use_litmus: true

Gemfile:
  required:
    ':development':
      - gem: 'toml-rb'

spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - 'RSpec.configure do |c|'
    - "  c.default_facter_version = '3.14.0'"
    - "  c.after(:suite) do"
    - "    RSpec::Puppet::Coverage.report!"
    - "  end"
    - "end"

Rakefile:
  requires:
    - require: 'puppet-strings/tasks'
      conditional: "Bundler.rubygems.find_name('puppet-strings').any?"
